const DB_USER = `parus`;
const DB_PASSWORD = `123z`;
const DB_CONNECTION_STRING = `192.168.1.112:1521/UDPPA`;


const PHONE_SIZE = 40;
const COMPANY_TITLE_SIZE = 160;
const CLIENT_NAME_SIZE = 160;
const MESSAGE_TEXT_SIZE = 2000;

module.exports = {
    DB_USER,
    DB_PASSWORD,
    DB_CONNECTION_STRING,
    PHONE_SIZE,
    COMPANY_TITLE_SIZE,
    CLIENT_NAME_SIZE,
    MESSAGE_TEXT_SIZE
};